filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        uppercase_constants: true
        use_self_instead_of_fqcn: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        overriding_parameter: true
        no_short_method_names:
            minimum: '3'
        no_short_variable_names:
            minimum: '2'
        no_long_variable_names:
            maximum: '25'
        no_goto: true
        newline_at_end_of_file: true
        line_length:
            max_length: '80'
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        function_in_camel_caps: true
        fix_line_ending: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        avoid_unnecessary_concatenation: true
        avoid_perl_style_comments: true
        avoid_todo_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true
        align_assignments: true

coding_style:
    php: {  }
